import { faker } from '@faker-js/faker'

export const jobsData = [
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
  {
    id: faker.string.uuid(),
    jobName: faker.person.jobTitle(),
    jobArea: faker.person.jobArea(),
    jobDescription: faker.person.jobDescriptor(),
    recruter: faker.person.fullName(),
    recruterAvatar: faker.image.avatar(),
    company: faker.company.name(),
    companyUrl: faker.internet.domainName(),
  },
]
